### ISSUE TITLE
"Hunted" player approximate location does not show for hunters unless they are very close

### ISSUE THREAD

**Issue by MineRaid** [tomezpl/sth-gamemode#21]

**Comment by tomezpl** [comment]
Hi @MineRaid. Are you using OneSync? I've re-tested the gamemode yesterday on a server with OneSync off and everything worked fine. I have heard replication may work differently with it enabled, and this gamemode doesn't account for that.

**Comment by MineRaid** [comment]
Hello @tomezpl. I was using OneSync at the time. Switching it off did allow me to see the markers.
